name: Infrastructure

services:
  kafka:
    image: apache/kafka:4.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,INTERNAL://:29092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,INTERNAL://kafka:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    healthcheck:
      test: [ "CMD-SHELL", "bash -lc 'echo > /dev/tcp/localhost/9092'" ]
      interval: 5s
      timeout: 3s
      retries: 30
    networks: [ feature-toggle ]

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
    depends_on:
      kafka:
        condition: service_healthy
    networks: [ feature-toggle ]

  feature-toggle-configuration-db-pg:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: feature_toggle_configuration
    ports:
      - "5432:5432"
    volumes:
      - projects-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d feature_toggle_configuration" ]
      interval: 5s
      timeout: 3s
      retries: 30
    networks: [ feature-toggle ]

  feature-toggle-write-db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: feature_toggle_write
    ports:
      - "5433:5432"
    volumes:
      - feature-toggle-write-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d feature_toggle_write" ]
      interval: 5s
      timeout: 3s
      retries: 30
    networks: [ feature-toggle ]

  feature-toggle-read-db-pg:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: feature_toggle_read
    ports:
      - "5434:5432"
    volumes:
      - feature-toggle-read-db-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d feature_toggle_read" ]
      interval: 5s
      timeout: 3s
      retries: 30
    networks: [ feature-toggle ]

volumes:
  projects-db-data:
  feature-toggle-write-db-data:
  feature-toggle-read-db-pg-data:

networks:
  feature-toggle:
    name: feature-toggle