app:
  upstream:
    toggleWrite: http://localhost:8082
    toggleConfiguration: http://localhost:8081

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/feature-toggle
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: toggleConfiguration
              uri: ${app.upstream.toggleConfiguration}
              predicates:
                - Path=/api/projects/**
              filters:
                - StripPrefix=1
                - PrefixPath=/rest/api

            - id: feature-toggle-write
              uri: ${app.upstream.toggleWrite}
              predicates:
                - Path=/api/projects/*/environments/*/feature-toggles/**
              filters:
                - StripPrefix=1
                - PrefixPath=/rest/api

server:
  port: 8090

