app:
  upstream:
    toggleWrite: http://localhost:8082
    toggleConfiguration: http://localhost:8081
    toggleRead: http://localhost:8083
    toggleAudit: http://localhost:8084

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/feature-toggle
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: toggleConfiguration
              order: 10
              uri: ${app.upstream.toggleConfiguration}
              predicates:
                - Path=/api/projects/**
              filters:
                - StripPrefix=1
                - PrefixPath=/rest/api

            - id: feature-toggle-write
              order: -10
              uri: ${app.upstream.toggleWrite}
              predicates:
                - Path=/api/projects/*/environments/*/feature-toggles,/api/projects/*/environments/*/feature-toggles/**
              filters:
                - StripPrefix=1
                - PrefixPath=/rest/api

            - id: feature-toggle-read
              order: -20
              uri: ${app.upstream.toggleRead}
              predicates:
                - Path=/api/read/**
              filters:
                - StripPrefix=1
                - PrefixPath=/rest/api

            - id: feature-toggle-sdk
              order: -20
              uri: ${app.upstream.toggleRead}
              predicates:
                - Path=/api/sdk/**
              filters:
                - StripPrefix=1
                - PrefixPath=/rest/api

            - id: feature-toggle-audit
              uri: ${app.upstream.toggleAudit}
              predicates:
                - Path=/api/audit/**
              filters:
                - StripPrefix=1
                - PrefixPath=/rest/api

server:
  port: 8090

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

