app:
  upstream:
    configlyToggleWrite: http://localhost:8082
    configlyStructure: http://localhost:8081
    configlyRead: http://localhost:8083
    configlyAudit: http://localhost:8084

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/feature-toggle
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: configlyStructure
              order: 10
              uri: ${app.upstream.configlyStructure}
              predicates:
                - Path=/api/projects/**
              filters:
                - StripPrefix=1
                - PrefixPath=/rest/api

            - id: configlyToggleWrite
              order: -10
              uri: ${app.upstream.configlyToggleWrite}
              predicates:
                - Path=/api/projects/*/environments/*/feature-toggles,/api/projects/*/environments/*/feature-toggles/**
              filters:
                - StripPrefix=1
                - PrefixPath=/rest/api

            - id: configlyRead
              order: -20
              uri: ${app.upstream.configlyRead}
              predicates:
                - Path=/api/read/**
              filters:
                - StripPrefix=1
                - PrefixPath=/rest/api

            - id: configly-sdk
              order: -20
              uri: ${app.upstream.configlyRead}
              predicates:
                - Path=/api/sdk/**
              filters:
                - StripPrefix=1
                - PrefixPath=/rest/api

            - id: configlyAudit
              uri: ${app.upstream.configlyAudit}
              predicates:
                - Path=/api/audit/**
              filters:
                - StripPrefix=1
                - PrefixPath=/rest/api

server:
  port: 8090

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

